# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest 2016 by GDG Coimbatore"
email: "gokulkarthickct@gmail.com"
description: "GDG DevFest is a set of events all around the world. This time, in Coimbatore. Come join us, meet the Googlers and share what you know with others."
baseurl: ""
url: "https://gdgcbe.com/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-74191160-2"
googleAnalyticsSiteUrl: "gdgcbe.com/"

# Organizer Info
organizerName: "GDG Coimbatore"
organizerAlternateName: "Google Developer Group Coimbatore"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gokulkarthickct@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://facebook.com/gdgcoimbatore/"

# Head
metaKeywords: "event, gdg, gdgcbe, devfest, google, programming, android, chrome, developers, coimbatore"
twitterAccount: "@gdgCoimbatore"
socialImageSrcGooglePlus: "/img/seo/hero.jpeg"
socialImageSrcTwitter: "/img/seo/hero.jpeg"
socialImageSrcFacebook: "/img/seo/hero.jpeg"

# Documents
c4pUrl: "mailto:gokulkarthickct@gmail.com"
c4sponsorsUrl: "mailto:gokulkarthickct@gmail.com"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 # - {permalink: "/logistics/", text: "Logistics"}
# Hero Block
heroImage: "hero.jpeg"
heroTitle: "A day for "
eventDate: "15th of October 2016"
typeoutTextValues: '"YOU","Programmers","Designers","Entrepreneurs","Startups"'
typeoutFallback: "Coimbatore"
heroButtons:
  - {link: "https://goo.gl/forms/JKCLGy1LvqK5R1Mz1", text: "Request for invite here"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lot's of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Unconference", image: "hackathon.jpg", text: "A brilliant GDG Coimbatore's Signature Unconference. This year, its much bigger and there's a surprise for you." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "500", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "2", specialCharacter: "", info: "Day", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "FORGE Accelerator"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "FORGE Accelerator, Kct Tech Park, Saravanapatti"
eventAddressLocality: "Coimbatore"
eventAddressLocalityRegion: "Tamil Nadu"
eventPostalCode: "641006"
eventAddressCountry: "India"
eventStartTime: "2016-10-15T08:30"
eventDoorTime: "09:00"
eventEndTime: "2016-10-15T17:00"
eventPlaceCoordinates: "11.0809746,76.9887196"
mapCenterCoordinates: "11.0809746,76.9887196"
mapMobileCenterCoordinates: "11.0809746,76.9887196"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_01.jpg"
venueSmallImage1: "venue_04.jpg"
venueSmallImage2: "venue_02.jpg"
venueSmallImage3: "venue_03.jpg"
venueTitle: "FORGE Accelerator"
venueFeatures: ["In the heart of the city", "Dolby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "cbedevfest"
twitterFeed: "http://www.varunraj.in/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://zathrac.us3.list-manage.com/subscribe/post?u=25748e12927120f75963019c3&amp;id=3ad8db8df7"
subscribeInfo: "Registration will be open around end of 11th Sep. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Registration"
ticketsOffers:
 -
  name: "Conference Ticket"
  price: "Invite Only"
  buyButtonLink: "https://goo.gl/forms/JKCLGy1LvqK5R1Mz1"
  buyButtonText: "Request here"
  ticketContentList: ["Conference on October 15th"]
  validFrom: "2016-09-18T23:59"
  validThrough: "2016-10-15T23:59"


# Footer
socialLinks:
 - {link: "https://developers.google.com/groups/chapter/107044365176730310412/", icon: "google-plus"}
 - {link: "https://twitter.com/GDGCoimbatore", icon: "twitter"}
 - {link: "https://facebook.com/GDGCoimbatore", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.gdgcbe.com", text: "GDG Coimbatore"}
   - {link: "https://developers.google.com/groups/pulse/India", text: "GDG India"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gokulkarthickct@gmail.com", text: "gokulkarthickct@gmail.com"}
   - {link: "https://twitter.com/gokulkarthickct", icon: "twitter"}
   - {link: "https://facebook.com/gokulkarthickct", icon: "facebook"}
   - {link: "mailto:", text: ""}


# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "11.0809746,76.9887196"
logisticsMapMobileCenterCoordinates: "11.0809746,76.9887196"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Coimbatore"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right inside the City. It is easily reachable by car, public transport or taxi. More information is available at airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Coimbatore. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Chennai.'}
 - {title: "Hotels", information: 'Coimbatore has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:


